server.port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      uri: mongodb+srv://doadmin:c90y8jJY54Me673i@portfolio-database-4ca3728e.mongo.ondigitalocean.com/admin?tls=true&authSource=admin
      authentication-database: admin
      auto-index-creation: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

okta:
  oauth2:
    issuer: https://dev-q4qzodi6wpd1thnb.us.auth0.com
    audience: https://dev-q4qzodi6wpd1thnb.us.auth0.com/api/v2/

auth0:
  domain: dev-q4qzodi6wpd1thnb.us.auth0.com
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://dev-q4qzodi6wpd1thnb.us.auth0.com/api/v2/
---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: portfolio
      username: root
      password: password
      authentication-database: admin